### ISSUE TITLE
"Party" returned with "Candidate" mismatch structure of that in party-endpoint

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#1]
I requested candidate-endpoint with param "_with=party". I found that the structure of candidate's "party" is not the same as that from party-endpoint. Date values return in different formats. I found different key names and structures, which confuses me. It'd be better if there is the same structure, key names, and value types for "party" in both endpoints.

**Comment by nyanlynnhtut** [comment]
Ping @tyohan @Mr-Zer0

**Comment by tyohan** [comment]
@phyominthu thanks for your issue. @Mr-Zer0 could you help us to make our party data format on candidate same with party endpoint. Thanks

**Comment by Mr-Zer0** [comment]
Sorry for lately reply. I will do it.
