### ISSUE TITLE
Ethnicity typo

### ISSUE THREAD

**Issue by khunzohn** [MyanmarAPI/candidate-endpoint#10]
The ethnicity of the candidate ' ဉီးဝင်းကို'  is incorrectly spelled 'ပအိုင်း'.'ပအိုဝ်း' should be used.

**Comment by tyohan** [comment]
@DragonVirus any comment on this Li?

**Comment by DragonVirus** [comment]
@tyohan yes ပအိုဝ်း is the right one.

**Comment by mapmeld** [comment]
I can't find  'ပအိုင်း' in the current dataset -- I think we are good
