### ISSUE TITLE
Please check the photo of Candidate id 81c1c57da09bfea87349b67b093990e0

### ISSUE THREAD

**Issue by dev-myatminsoe** [MyanmarAPI/candidate-endpoint#12]
The photo is just white plain image with တု on top of the image. Make no sense

**Comment by tyohan** [comment]
@mapmeld can you check form Scan_C_20150831_008.jpg

**Comment by mapmeld** [comment]
@tyohan use a JPEG of this photo 
![screen shot 2015-10-02 at 4 20 38 pm](https://cloud.githubusercontent.com/assets/643918/10243856/95a5c70e-6921-11e5-8146-1e8e446e81fc.png)

**Comment by tyohan** [comment]
Photo updated @septemberboy7 @mapmeld
