### ISSUE TITLE
Empty string in gender field of four candidates

### ISSUE THREAD

**Issue by yewintaung** [MyanmarAPI/candidate-endpoint#13]
there are 4 candidates whose gender field is neither 'M' nor 'F'.
It is in empy string. They are,

17a6a1161459792855b01866bb2ba9ba
31a8cd8291fcae78028be555e2a6a47a
3424c2d1bf5b36be7c80d1a7b4ed5f5f
5f67d03c2b7d9b3e99eb0fa6e0e8ec97

**Comment by mapmeld** [comment]
Names all begin with ဦး​ ... these will be marked M in the next update
