### ISSUE TITLE
Two Lower House Candidate's constituency dt_pcode and st_pcode is NULL.

### ISSUE THREAD

**Issue by yewintaung** [MyanmarAPI/candidate-endpoint#14]
All of the lower house candidate's constituency dt_pcode and st_pcode is not null except following two candidates.
96c3b9809029872d76926a434501ce34
a0008f3fbf6948c46b8a8f1538fbeef3

And these two candidate's constituency name in unicode is corrupted like
���င်ပေါင်ဝဲမြို့နယ်
မိုင်းဖြတ်မဲဆန္ဒနယ���

**Comment by mapmeld** [comment]
ok, there are about 20 corrupted chars in the dataset
went back in and these will be fixed in the next update
