### ISSUE TITLE
Candidate's "party" response data is empty when query using "fields"

### ISSUE THREAD

**Issue by infinityzero** [MyanmarAPI/candidate-endpoint#15]
When request [this link](http://api.maepaysoh.org/candidate/list?token=my_token&_with=party&fields=id,name,photo_url,party&font=unicode&per_page=1&page=1), `party` field's value in response data is empty like that `party: {}`.

**Comment by DragonVirus** [comment]
@infinityzero to include party embedded data you need to request `party_id`field.
