### ISSUE TITLE
Candidate id 27a39da90e7bdb4674d1aed3e9314654 photo is wrong

### ISSUE THREAD

**Issue by dev-myatminsoe** [MyanmarAPI/candidate-endpoint#16]
The photo of candidate 27a39da90e7bdb4674d1aed3e9314654 is wrong.

**Comment by mapmeld** [comment]
@tyohan use attached as JPG 
![screen shot 2015-10-04 at 7 11 14 pm](https://cloud.githubusercontent.com/assets/643918/10267880/c84cd958-6acb-11e5-9fc7-a47c34a024bf.png)

**Comment by tyohan** [comment]
@septemberboy7 done replace the image. Thanks for remind.
