### ISSUE TITLE
No State/Region Candidate from Township MMR006005

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#18]
Hi,

I found no state/region hluttaw candidates for township with Pcode MMR006005. Is this correct or the data error?

Thanks.

**Comment by mapmeld** [comment]
thanks for catching this! we have seven candidates who should be in this township in the next data update

**Comment by phyominthu** [comment]
Just checked and it looks like this isn't updated on API yet.
