### ISSUE TITLE
candidate 077dbf72a7c2e306fa35498de9bfb2ea has wrong birthday

### ISSUE THREAD

**Issue by dev-myatminsoe** [MyanmarAPI/candidate-endpoint#19]
He(the candidate) reported me directly. The correct date is 28th June 1980. The current date is 19th June 1980.

**Comment by tyohan** [comment]
@mapmeld check the form they fill, we only able to change based on form. cc @septemberboy7

**Comment by mapmeld** [comment]
@septemberboy7 thanks for reporting this! I checked the form and it is 28 June 1980. It will be corrected in the next update.
