### ISSUE TITLE
Un-necessary 'data' key in 'party' returned with Candidate

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#2]
Hi,

Just a tiny suggestion. This `data` key in candidate's `party` looks unnecessary. I should be able to get party properties straight under the `party`. Sorry if I sounded too mean.

![screen shot 2015-09-08 at 3 49 12 pm](https://cloud.githubusercontent.com/assets/6995089/9731322/334e5888-5642-11e5-93bd-43d8a0947675.png)

Thanks!

**Comment by tyohan** [comment]
No worries, more issues posted means you guys more awesome because you care about this open source code :) 

Anyway the reason we make it that way because we have a _meta property so we can put some meta information on it.

**Comment by phyominthu** [comment]
Hmm.. I don't see `_meta` in `party` which is included in the candidate data. Of course, there's `_meta` for party in **party-endpoint**. But is this necessary here at **candidate-endpoint**? Also there's already `data` and `meta` in the uppermost level in the response of this endpoint.

![screen shot 2015-09-08 at 11 15 34 pm](https://cloud.githubusercontent.com/assets/6995089/9741278/917211d8-567f-11e5-952a-7f094d64d079.png)

**Comment by tyohan** [comment]
Oh i got your point. @DragonVirus could you check this one. I think it's better not wrap the party inside data. Just put it directly under party-node. Hopefully it's not affected to our SDK.

**Comment by tyohan** [comment]
@DragonVirus please update also on documentation

**Comment by DragonVirus** [comment]
Fixed
