### ISSUE TITLE
No State/Region Candidate from Township MMR009013

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#20]
Hi,

I don't see any state/region candidates for township with Pcode `MMR009013`. Is it correct or data error?

**Comment by mapmeld** [comment]
those candidates are combined with the other မင်းလှမဲဆန္ဒနယ် in ပဲခူးတိုင်းဒေသကြီး ... will separate the two in a later update

**Comment by mapmeld** [comment]
OK figured this out, and the other constituency are going to be fixed in the next update
