### ISSUE TITLE
API Routes Consistency

### ISSUE THREAD

**Issue by dreamingblackcat** [MyanmarAPI/candidate-endpoint#3]
I know this is a controversial topic. But consistency is important in APIs , IMO. Currently,
- Collection Route for candidates use `/candidate/list` while collection route for parties use just `/party` .
- Singular Route for candidates use `/candidate/:id` while singular route for parties use `/party/detail/:id`.

Please feel free to close this issue if you think it's irrelevant.

**Comment by tyohan** [comment]
Thanks for the input. We aware this consistency issue, but due on SDK that we already develop, we can't change our endpoint format for now because it will make our SDK doesn't work. This is happen because our endpoint develop by different developers. So i think I will close it for now
