### ISSUE TITLE
"Party" returned with "Candidate" has different date formats of that in party-endpoint

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#5]
Hi,

I found different date formats for `party` in candidate-endpoint and party-endpoint. I heard party-endpoint cannot be easily changed. If so, could you please make these date formats in candidate-endpoint consistent with party-endpoint?

Date format of `party` in **party-endpoint**
![screen shot 2015-09-11 at 11 45 03 am](https://cloud.githubusercontent.com/assets/6995089/9807566/e9e6ada4-587a-11e5-8eff-5a86d649ef92.png)

Date format of candidate's `party` in **candidate-endpoint**
![screen shot 2015-09-11 at 11 45 35 am](https://cloud.githubusercontent.com/assets/6995089/9807567/ec7b1e60-587a-11e5-9624-5ba19f6ad6b3.png)

**Comment by nyanlynnhtut** [comment]
Ping @tyohan 
We used timestamp format for date time. Can u change these format for party api?

**Comment by tyohan** [comment]
Noted, we will convert it to use timestamp. @phyominthu @nyanlynnhtut
