### ISSUE TITLE
Inconsistent key names and confusing party IDs

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#6]
Hi,

There is `party_id` in candidate-endpoint which is the same value as `party_number` in **party-endpoint**. And in `party` of the candidate, there are `id` and `party_id`, which is confusing, so could you make it as `party_number`?

Party of candidate in **candidate-endpoint** (Two IDs is confusing)
![screen shot 2015-09-12 at 10 40 59 pm](https://cloud.githubusercontent.com/assets/6995089/9832396/a8303e90-599f-11e5-854f-71c1fb7bfa66.png)

Party in **party-endpoint**
![screen shot 2015-09-12 at 10 41 21 pm](https://cloud.githubusercontent.com/assets/6995089/9832395/a7e21710-599f-11e5-88f8-3b1b591aff5c.png)

Thanks.

**Comment by phyominthu** [comment]
Is it possible to changed this too? This is directly under `candidate`.

![screen shot 2015-09-12 at 11 43 46 pm](https://cloud.githubusercontent.com/assets/6995089/9832666/3ba0aec8-59a8-11e5-9e7b-d7f573d4ece2.png)

I think you also have to change the doc if you do this.

**Comment by DragonVirus** [comment]
@phyominthu which one do you mean ?

**Comment by phyominthu** [comment]
`party_id` in candidate. Is it okay to change that to `party_number`?

**Comment by phyominthu** [comment]
Ugh. There's also `approved_party_number`. I'm confusing between `id`, `party_id`, `party_number`, and `approved_party_number` now. What is what? :(

**Comment by DragonVirus** [comment]
`approved_party_number` is their official approval party number. 
You should use `_id` to connect with other endpoint.

**Comment by phyominthu** [comment]
The API is not changing as the commit yet. It still showing `party_id` instead of `party_number` @DragonVirus

**Comment by DragonVirus** [comment]
@phyominthu sorry it should be changed by now. please check again.

**Comment by phyominthu** [comment]
And here is another inconsistency. There is `party_id` directly under `candidate`. I think it should be renamed to `party_number` like you did inside `party`. Will this break the SDK? I'm not sure.

_In below image, You can see `party_id` of the candidate and `party_numer` of the party sharing the same value_
![screen shot 2015-09-13 at 2 54 45 pm](https://cloud.githubusercontent.com/assets/6995089/9835910/8485dd3c-5a27-11e5-998c-95da78845ad0.png)

**Comment by DragonVirus** [comment]
@phyominthu now i also changed that to party_number

**Comment by DragonVirus** [comment]
@phyominthu now we changed the `party_number` to `id` in party endpoint and to `party_id` in candidate endpoint. We won't use hexstring `_id` anymore for party.
Sorry about the inconvenience. Some changes happened cuz the data structures are changed a bit when the real data came in. 
Thanks for all your contributions.

**Comment by phyominthu** [comment]
Wow. I've been waiting so long for this fix. It's crystal clear about Party IDs now. Thanks.
