### ISSUE TITLE
Candidate name autocomplete

### ISSUE THREAD

**Issue by Wyclef** [MyanmarAPI/candidate-endpoint#7]
Could you please add an autocomplete feature for candidates?

I just want an API function that returns something like 10 results for candidates whose names start with the string I sent.

**Comment by DragonVirus** [comment]
@Wyclef You can request like this http://api.maepaysoh.org/candidate/search?q=ဝင်းမောင်&token={{token}}

**Comment by Wyclef** [comment]
@DragonVirus Yes thanks but it returns a lot of data. My request is to return only a list of names and IDs because I'll be calling the API as the user types so too much data is undesirable.

**Comment by Wyclef** [comment]
@DragonVirus Yes thanks but it returns a lot of data. My request is to return only a list of names and IDs because I'll be calling the API as the user types so too much data is undesirable.

**Comment by DragonVirus** [comment]
commit 97488d7ddbbcd7266d59b0e2925d90987dd4e0fc fix the problem.
