### ISSUE TITLE
Cannot get candidates for certain "Upper House Constituency"

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/candidate-endpoint#8]
Hi,

This is the data returned for **an upper house constituency** from **geo-endpoint**.
![screen shot 2015-09-16 at 2 52 43 pm](https://cloud.githubusercontent.com/assets/6995089/9899904/f4004f28-5c82-11e5-854f-cabc1d4968e8.png)

But I can't think a way to find candidates for a certain **Upper House constituency** at **candidate-endpoint**. I cannot filter out by state name/pcode for Upper House Candidates. The Pcode values are `null`s when I search with param `legislature=အမျိုးသားလွှတ်တော်`. The Upper House candidates should have some relationship with the constituency location like **a Pcode for that area** (I think it's there in geo-endpoint "MMR001HLA001") to query. They should also be searched with `st_name`, `st_pcode`, along with _constituency number_.
![screen shot 2015-09-16 at 2 52 18 pm](https://cloud.githubusercontent.com/assets/6995089/9899959/4f53528a-5c83-11e5-8b60-a1eb6b377435.png)

**Comment by Wyclef** [comment]
Exactly man. I've been stumped by it also. Right now, we cannot link upper house candidates to any location, except what is give in the "name" attribute.
